### ISSUE TITLE
Assign a group to newly imported ADMX files?

### ISSUE THREAD

**Issue by SGeeves** [sandytsang/MSIntune#2]
Currently there is no easy was to import the files and assign a group to the policy created.
Has anyone been able to look into this and found a solution (I have tried and failed).

**Comment by SGeeves** [comment]
Function` Add-GroupPolicyConfigurationsAssignment(){

<#
.SYNOPSIS
This function is used to add a device compliance policy assignment using the Graph API REST interface
.DESCRIPTION
The function connects to the Graph API Interface and adds a device compliance policy assignment
.EXAMPLE
Add-DeviceCompliancePolicyAssignment -CompliancePolicyId $CompliancePolicyId -TargetGroupId $TargetGroupId
Adds a device compliance policy assignment in Intune
.NOTES
NAME: Add-DeviceCompliancePolicyAssignment
#>

[cmdletbinding()]

param
(
    $GroupPolicyId,
    $TargetGroupId
)

$graphApiVersion = "beta"
$Resource = "deviceManagement/groupPolicyConfigurations/$GroupPolicyId/assign"
    
    try {

        if(!$GroupPolicyId){

        write-host "No Compliance Policy Id specified, specify a valid Compliance Policy Id" -f Red
        break

        }

        if(!$TargetGroupId){

        write-host "No Target Group Id specified, specify a valid Target Group Id" -f Red
        break

        }

$JSON = @"

    {
        "assignments": [
        {
            "target": {
            "@odata.type": "#microsoft.graph.groupAssignmentTarget",
            "groupId": "$TargetGroupId"
            }
        }
        ]
    }
    
"@

    $uri = "https://graph.microsoft.com/$graphApiVersion/$($Resource)"
    Invoke-RestMethod -Uri $uri -ContentType "application/json" -Headers $authToken -Method Post -Body $JSON

    }
    
    catch {

    $ex = $_.Exception
    $errorResponse = $ex.Response.GetResponseStream()
    $reader = New-Object System.IO.StreamReader($errorResponse)
    $reader.BaseStream.Position = 0
    $reader.DiscardBufferedData()
    $responseBody = $reader.ReadToEnd();
    Write-Host "Response content:`n$responseBody" -f Red
    Write-Error "Request to $Uri failed with HTTP Status $($ex.Response.StatusCode) $($ex.Response.StatusDescription)"
    write-host
    break

    }

}

**Comment by abenum** [comment]
How can I get the Group Policy ID with a script?
I tried this, but is gives me IDs for all policies, so its useless with the command 
"Add-GroupPolicyConfigurationsAssignment -GroupPolicyId $GroupPolicyConfigurationID -TargetGroupId $TargetGroupId"

`
Function Get-GroupPolicyID(){

<#
Finds GroupPolicy ID
#>

[cmdletbinding()]

param
(
    $Name,
    $graphApiVersion = "v1.0"
)

$Resource = "deviceManagement/groupPolicyConfigurations"

    try {

        
        $uri = "https://graph.microsoft.com/beta/deviceManagement/groupPolicyConfigurations/"
        $GroupPolicyResponse = (Invoke-RestMethod -Uri $uri -Headers $authToken -Method Get).value
        $GroupPolicyID = $GroupPolicyResponse.id
        return $GroupPolicyID 

    }

    catch {

    $ex = $_.Exception
    $errorResponse = $ex.Response.GetResponseStream()
    $reader = New-Object System.IO.StreamReader($errorResponse)
    $reader.BaseStream.Position = 0
    $reader.DiscardBufferedData()
    $responseBody = $reader.ReadToEnd();
    Write-Host "Response content:`n$responseBody" -f Red
    Write-Error "Request to $Uri failed with HTTP Status $($ex.Response.StatusCode) $($ex.Response.StatusDescription)"
    write-host
    break

    }

}`
