### ISSUE TITLE
Unable to assign group to imported ADMX files

### ISSUE THREAD

**Issue by SGeeves** [sandytsang/MSIntune#5]
Hi There, love the scripts! Fantastic work.

Just one thing, when using the DeviceConfigurationADMX_Import_FromJSON.ps1.
There is no option to assign a group to the newly imported ADMX template. The import works great, but would be amazing if we could have the functionality to assign a targetgroupid to the policy!

Keep doing what you're doing :D

**Comment by SGeeves** [comment]
Function Add-GroupPolicyConfigurationsAssignment(){

<#
.SYNOPSIS
This function is used to add a device compliance policy assignment using the Graph API REST interface
.DESCRIPTION
The function connects to the Graph API Interface and adds a device compliance policy assignment
.EXAMPLE
Add-DeviceCompliancePolicyAssignment -CompliancePolicyId $CompliancePolicyId -TargetGroupId $TargetGroupId
Adds a device compliance policy assignment in Intune
.NOTES
NAME: Add-DeviceCompliancePolicyAssignment
#>

[cmdletbinding()]

param
(
    $GroupPolicyId,
    $TargetGroupId
)

$graphApiVersion = "beta"
$Resource = "deviceManagement/groupPolicyConfigurations/$GroupPolicyId/assign"
    
    try {

        if(!$GroupPolicyId){

        write-host "No Compliance Policy Id specified, specify a valid Compliance Policy Id" -f Red
        break

        }

        if(!$TargetGroupId){

        write-host "No Target Group Id specified, specify a valid Target Group Id" -f Red
        break

        }

$JSON = @"

    {
        "assignments": [
        {
            "target": {
            "@odata.type": "#microsoft.graph.groupAssignmentTarget",
            "groupId": "$TargetGroupId"
            }
        }
        ]
    }
    
"@

    $uri = "https://graph.microsoft.com/$graphApiVersion/$($Resource)"
    Invoke-RestMethod -Uri $uri -ContentType "application/json" -Headers $authToken -Method Post -Body $JSON

    }
    
    catch {

    $ex = $_.Exception
    $errorResponse = $ex.Response.GetResponseStream()
    $reader = New-Object System.IO.StreamReader($errorResponse)
    $reader.BaseStream.Position = 0
    $reader.DiscardBufferedData()
    $responseBody = $reader.ReadToEnd();
    Write-Host "Response content:`n$responseBody" -f Red
    Write-Error "Request to $Uri failed with HTTP Status $($ex.Response.StatusCode) $($ex.Response.StatusDescription)"
    write-host
    break

    }

}

**Comment by sandytsang** [comment]
@SGeeves Hi, thank you! I was going to ask you if you would like to contribute and maybe make a pull request 😄 I will take a look your script and merge this. Have a nice weekend!
