### ISSUE TITLE
ADMX_Export.ps1 don't export anything at all

### ISSUE THREAD

**Issue by diegopozzi1** [sandytsang/MSIntune#7]
Hi, I'm trying to export my MEM policy, unfortunately it doesn't export anything at all. What I'm doing wrong? when grants where asked for the first time I've flagged "consent on behalf ..."

How I could check the grant and verify that are fine? someone else has the same problem I'm having?

**Comment by sandytsang** [comment]
If this is first time you use Intune graph API do anything with PowerShell, it requires Global Admin to give admin consent to the API. See in the code, you will find the appid.

**Comment by diegopozzi1** [comment]
Hi, sorry for the long delay in reply. I've used the global admin login when prompted and selected all the check boxes and "consent on behalf of your organization" too but still, it don't export anything :-/

**Comment by diegopozzi1** [comment]
Maybe I got it but still I have problems, with the old version found on https://deviceadvice.io/2019/07/12/export-import-your-intune-tenant-settings/ it export at least the update ring, with the latest version it doesn't export anything at all and with your ones export the ADMX settings only, is that right?

![export](https://user-images.githubusercontent.com/93269508/140324457-03a2d793-960a-437e-b11f-14758dde25e7.png)

**Comment by sandytsang** [comment]
@diegopozzi1  the script from Microsoft Intune example Github doesn't cover ADMX export and import.
My script covers only ADMX export and import, not other settings

**Comment by diegopozzi1** [comment]
probably there is a problem with the latest version :-/
about your one, it works perfectly then , thanks for answering :-)

**Comment by tovarisUmek** [comment]
Hi, 
is this script still supposed to work? 
It creates folder for me, but inside the folder i dont get any .json files. 
Any help please.
![image](https://github.com/sandytsang/MSIntune/assets/154511271/d36ca3fc-1a5b-457b-9984-83c6c6e50b05)

**Comment by sandytsang** [comment]
> Hi, 
> 
> is this script still supposed to work? 
> 
> It creates folder for me, but inside the folder i dont get any .json files. 
> 
> Any help please.
> 
> ![image](https://github.com/sandytsang/MSIntune/assets/154511271/d36ca3fc-1a5b-457b-9984-83c6c6e50b05)
> 
> 

Hi. I have not use my own script for long time, not sure if it still works. There is a better tool for this, and have UI as well. Please take a look. I am using his tool mostly. 

https://github.com/Micke-K/IntuneManagement

Regards, Sandy

**Comment by tovarisUmek** [comment]
Thank you!
https://github.com/Micke-K/IntuneManagement - is what I need.
